# Generated by Django 4.2.21 on 2026-02-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_policies', '0003_update_passwordprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangerequired',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
